# Generated by Django 4.2.1 on 2023-06-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('trip_price', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('seat', models.IntegerField()),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('amenities', models.ManyToManyField(to='myapp.amenities')),
            ],
            options={
                'db_table': 'myapp_Car',
            },
        ),
        migrations.CreateModel(
            name='car_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='car')),
                ('cars_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='myapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
                ('drop', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('half', 'half'), ('full', 'full')], max_length=100)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_booking', to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='trip',
        ),
    ]
