# Generated by Django 4.2.1 on 2023-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='first',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
