# Generated by Django 4.2.1 on 2023-06-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_booking_drop_city_booking_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup',
            new_name='pickup_city',
        ),
    ]
